"use client";

import { CheckCircle2, FileText, Loader2 } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useLocale, useTranslations } from "next-intl";

import { AsyncStateCard } from "@/components/feedback/AsyncStateCard";
import { PageHeader } from "@/components/layout/PageHeader";
import { SavingsBar } from "@/components/savings/SavingsBar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { fetchApi } from "@/lib/api-client";
import {
  readApiErrorMessage,
  resolveApiErrorMessage,
} from "@/lib/client-errors";
import {
  RESOLUTION_EXPORT_FEATURE_KEYS,
  STANDARD_EXPORT_FEATURE_KEYS,
} from "@/lib/exports/view";
import type { ExportCasePayload, ExportDownloadPayload } from "@/types/export";

async function parseJsonBody<T>(response: Response): Promise<T | null> {
  const rawBody = await response.text();

  if (!rawBody) {
    return null;
  }

  try {
    return JSON.parse(rawBody) as T;
  } catch {
    return null;
  }
}

function readPayloadErrorMessage(
  payload: { error?: string | { message?: string } } | null,
) {
  if (!payload?.error) {
    return null;
  }

  if (typeof payload.error === "string") {
    return payload.error;
  }

  if (typeof payload.error.message === "string") {
    return payload.error.message;
  }

  return null;
}

export default function ExportPage({
  params: { caseId },
}: {
  params: { caseId: string };
}) {
  const locale = useLocale();
  const t = useTranslations();
  const searchParams = useSearchParams();
  const [caseStatus, setCaseStatus] = useState<
    ExportCasePayload["case"]["status"] | null
  >(null);
  const [viewerRole, setViewerRole] = useState<
    ExportCasePayload["case"]["viewer_role"] | null
  >(null);
  const [initiatorSatisfiedAt, setInitiatorSatisfiedAt] = useState<
    string | null
  >(null);
  const [responderSatisfiedAt, setResponderSatisfiedAt] = useState<
    string | null
  >(null);
  const [autoGenerateDueAt, setAutoGenerateDueAt] = useState<string | null>(
    null,
  );
  const [isMarkingComplete, setIsMarkingComplete] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isCheckingOut, setIsCheckingOut] = useState<
    "standard" | "resolution" | null
  >(null);
  const [isPolling, setIsPolling] = useState(false);
  const [downloadUrl, setDownloadUrl] = useState("");
  const [downloadTier, setDownloadTier] = useState<"standard" | "resolution">(
    "standard",
  );
  const [errorMessage, setErrorMessage] = useState("");

  const isSuccess = searchParams.get("success") === "true";
  const isCancelled = searchParams.get("cancelled") === "true";
  const isSingleParty = caseStatus === "expired";
  const canPurchaseExport = viewerRole === "initiator";
  const viewerSatisfied =
    viewerRole === "initiator"
      ? Boolean(initiatorSatisfiedAt)
      : Boolean(responderSatisfiedAt);
  const otherSatisfied =
    viewerRole === "initiator"
      ? Boolean(responderSatisfiedAt)
      : Boolean(initiatorSatisfiedAt);
  const exportUnlocked =
    isSingleParty ||
    (Boolean(initiatorSatisfiedAt) && Boolean(responderSatisfiedAt)) ||
    (Boolean(initiatorSatisfiedAt || responderSatisfiedAt) &&
      Boolean(autoGenerateDueAt) &&
      new Date(autoGenerateDueAt as string).getTime() <= Date.now());
  const hasReadyExport = Boolean(downloadUrl);
  const currentStage = useMemo(
    () => (hasReadyExport || isSuccess ? 5 : 4),
    [hasReadyExport, isSuccess],
  );
  const showReadyExportCard = hasReadyExport || isSuccess;

  const loadDownloadStatus = useCallback(async () => {
    const response = await fetchApi(`/api/exports/${caseId}/download`, locale, {
      cache: "no-store",
    });

    const payload = await parseJsonBody<ExportDownloadPayload>(response);

    if (!response.ok) {
      if (response.status === 404) {
        setDownloadUrl("");
        return null;
      }

      throw new Error(
        resolveApiErrorMessage(
          readPayloadErrorMessage(payload),
          t("export.loadError"),
        ),
      );
    }

    if (!payload?.download_url) {
      setDownloadUrl("");
      return null;
    }

    setDownloadUrl(payload.download_url);
    setDownloadTier(payload.tier ?? "standard");
    return payload;
  }, [caseId, locale, t]);

  useEffect(() => {
    let ignore = false;

    async function loadPageData() {
      try {
        const caseResponse = await fetchApi(`/api/cases/${caseId}`, locale, {
          cache: "no-store",
        });

        if (!caseResponse.ok) {
          throw new Error(
            resolveApiErrorMessage(
              await readApiErrorMessage(caseResponse),
              t("export.loadError"),
            ),
          );
        }

        const casePayload = (await caseResponse.json()) as ExportCasePayload;
        const exportPayload = await loadDownloadStatus();

        if (!ignore) {
          setCaseStatus(casePayload.case.status);
          setViewerRole(casePayload.case.viewer_role);
          setInitiatorSatisfiedAt(casePayload.case.initiator_satisfied_at);
          setResponderSatisfiedAt(casePayload.case.responder_satisfied_at);
          setAutoGenerateDueAt(casePayload.case.auto_generate_due_at);
          setErrorMessage("");
          if (!exportPayload?.download_url) {
            setDownloadUrl("");
          }
        }
      } catch (error) {
        if (!ignore) {
          setErrorMessage(
            error instanceof Error && error.message
              ? error.message
              : t("export.loadError"),
          );
        }
      } finally {
        if (!ignore) {
          setIsLoading(false);
        }
      }
    }

    void loadPageData();

    return () => {
      ignore = true;
    };
  }, [caseId, loadDownloadStatus, locale, t]);

  useEffect(() => {
    if (!isSuccess) {
      return;
    }

    let ignore = false;
    let intervalId: NodeJS.Timeout | null = null;

    async function pollDownload() {
      try {
        const payload = await loadDownloadStatus();

        if (!payload) {
          return;
        }

        if (!ignore && payload.download_url) {
          setIsPolling(false);
          if (intervalId) {
            clearInterval(intervalId);
          }
        }
      } catch {}
    }

    if (!downloadUrl) {
      setIsPolling(true);
      void pollDownload();
      intervalId = setInterval(() => {
        void pollDownload();
      }, 5000);
    }

    return () => {
      ignore = true;
      if (intervalId) {
        clearInterval(intervalId);
      }
    };
  }, [downloadUrl, isSuccess, loadDownloadStatus]);

  async function handleCheckout(tier: "standard" | "resolution") {
    if (!canPurchaseExport) {
      setErrorMessage(t("export.initiatorOnlyBody"));
      return;
    }

    setErrorMessage("");
    setIsCheckingOut(tier);

    try {
      const response = await fetchApi("/api/payments/checkout", locale, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          case_id: caseId,
          tier,
        }),
      });

      const payload =
        (await parseJsonBody<{ error?: string; url?: string }>(response)) ?? {};

      if (!response.ok || !payload.url) {
        throw new Error(
          resolveApiErrorMessage(payload.error, t("errors.generic")),
        );
      }

      window.location.href = payload.url;
    } catch (error) {
      setErrorMessage(
        error instanceof Error && error.message
          ? error.message
          : t("errors.generic"),
      );
      setIsCheckingOut(null);
    }
  }

  async function handleMarkSatisfied() {
    setErrorMessage("");
    setIsMarkingComplete(true);

    try {
      const response = await fetchApi(
        `/api/cases/${caseId}/completion`,
        locale,
        {
          method: "PATCH",
        },
      );

      const payload = (await response.json()) as {
        error?: string;
        case?: ExportCasePayload["case"];
      };

      if (!response.ok || !payload.case) {
        throw new Error(
          resolveApiErrorMessage(payload.error, t("export.markCompleteError")),
        );
      }

      setInitiatorSatisfiedAt(payload.case.initiator_satisfied_at);
      setResponderSatisfiedAt(payload.case.responder_satisfied_at);
      setAutoGenerateDueAt(payload.case.auto_generate_due_at);
      setCaseStatus(payload.case.status);
    } catch (error) {
      setErrorMessage(
        error instanceof Error && error.message
          ? error.message
          : t("export.markCompleteError"),
      );
    } finally {
      setIsMarkingComplete(false);
    }
  }

  async function handleSinglePartyDownload() {
    setErrorMessage("");
    setIsPolling(true);

    try {
      const response = await fetchApi(
        `/api/exports/${caseId}/download`,
        locale,
        {
          cache: "no-store",
        },
      );
      const payload = (await response.json()) as ExportDownloadPayload;

      if (!response.ok || !payload.download_url) {
        throw new Error(
          resolveApiErrorMessage(
            readPayloadErrorMessage(payload),
            t("errors.generic"),
          ),
        );
      }

      setDownloadUrl(payload.download_url);
      setDownloadTier(payload.tier ?? "standard");
      window.location.href = payload.download_url;
    } catch (error) {
      setErrorMessage(
        error instanceof Error && error.message
          ? error.message
          : t("errors.generic"),
      );
    } finally {
      setIsPolling(false);
    }
  }

  if (isLoading) {
    return (
      <main className=" px-5 py-6">
        <div className="mx-auto max-w-6xl">
          <PageHeader
            brandLabel={t("nav.brand")}
            locale={locale}
            subtitle={t("export.loading")}
            title={t("export.title")}
            titleClassName="text-3xl sm:text-4xl"
          />
          <AsyncStateCard
            body={t("export.ready")}
            title={t("export.loading")}
          />
        </div>
      </main>
    );
  }

  return (
    <main className=" px-5 py-6">
      <div className="mx-auto max-w-6xl space-y-6">
        <PageHeader
          brandLabel={t("nav.brand")}
          eyebrow={t("export.eyebrow")}
          locale={locale}
          subtitle={t("export.ready")}
          title={t("export.title")}
        />

        <SavingsBar stage={currentStage} tier={downloadTier} />

        {!isLoading && caseStatus ? (
          <Card className="app-panel border-brand/15">
            <CardContent className="space-y-2 p-6">
              <p className="app-kicker">{t("export.nextStepLabel")}</p>
              <p className="text-sm leading-6 text-ink-soft">
                {hasReadyExport
                  ? t("export.successReady")
                  : isSingleParty
                    ? t("export.nextStepSingleParty")
                    : exportUnlocked && canPurchaseExport
                      ? t("export.nextStepInitiator")
                      : exportUnlocked
                        ? t("export.nextStepResponder")
                        : canPurchaseExport
                          ? t("export.nextStepAwaitingConfirmation")
                          : t("export.nextStepResponderConfirmation")}
              </p>
            </CardContent>
          </Card>
        ) : null}

        {!isSingleParty && !exportUnlocked ? (
          <Card className="app-panel border-brand/15">
            <CardContent className="space-y-4 p-6">
              <div className="space-y-2">
                <h2 className="font-display text-2xl text-ink">
                  {t("export.confirmationTitle")}
                </h2>
                <p className="text-sm leading-6 text-ink-soft">
                  {viewerSatisfied
                    ? t("export.confirmationRecorded")
                    : t("export.confirmationBody")}
                </p>
              </div>

              <div className="grid gap-3 md:grid-cols-2">
                <div className="app-note bg-surface-soft px-4 py-3 text-sm">
                  <p className="text-xs font-semibold uppercase tracking-[0.2em] text-ink-soft">
                    {t("export.yourConfirmationStatus")}
                  </p>
                  <p className="mt-2 font-medium text-ink">
                    {viewerSatisfied
                      ? t("export.confirmed")
                      : t("export.awaitingYourConfirmation")}
                  </p>
                </div>
                <div className="app-note bg-surface-soft px-4 py-3 text-sm">
                  <p className="text-xs font-semibold uppercase tracking-[0.2em] text-ink-soft">
                    {t("export.otherConfirmationStatus")}
                  </p>
                  <p className="mt-2 font-medium text-ink">
                    {otherSatisfied
                      ? t("export.confirmed")
                      : t("export.awaitingOtherConfirmation")}
                  </p>
                </div>
              </div>

              {autoGenerateDueAt ? (
                <p className="text-sm leading-6 text-ink-soft">
                  {t("export.autoGenerateDue", {
                    date: new Date(autoGenerateDueAt).toLocaleDateString(
                      locale,
                    ),
                  })}
                </p>
              ) : null}

              {!viewerSatisfied ? (
                <Button
                  className="h-12 px-6 text-base"
                  disabled={isMarkingComplete}
                  size="lg"
                  type="button"
                  onClick={() => void handleMarkSatisfied()}
                >
                  {isMarkingComplete
                    ? t("export.markingComplete")
                    : t("export.markSatisfied")}
                </Button>
              ) : null}
            </CardContent>
          </Card>
        ) : null}

        {showReadyExportCard ? (
          <Card className="app-panel">
            <CardContent className="space-y-4 p-6">
              <div className="app-icon-chip">
                <CheckCircle2 className="size-5" />
              </div>
              <div className="space-y-2">
                <h2 className="font-display text-3xl text-ink">
                  {t("export.successTitle")}
                </h2>
                <p className="text-sm leading-6 text-ink-soft">
                  {downloadUrl
                    ? t("export.successReady")
                    : t("export.successPreparing")}
                </p>
              </div>
              {downloadUrl ? (
                <Button
                  className="h-12 px-6 text-base"
                  size="lg"
                  type="button"
                  onClick={() => {
                    window.location.href = downloadUrl;
                  }}
                >
                  {t("export.downloadReady")}
                </Button>
              ) : (
                <div className="app-note flex items-center gap-3 px-4 py-4">
                  <Loader2 className="size-4 animate-spin" />
                  <span>{t("export.polling")}</span>
                </div>
              )}
            </CardContent>
          </Card>
        ) : null}

        {isCancelled ? (
          <Card className="border-warning/15">
            <CardContent className="p-6 text-sm leading-6 text-warning-foreground">
              {t("export.cancelled")}
            </CardContent>
          </Card>
        ) : null}

        {!hasReadyExport && isSingleParty ? (
          <Card className="app-panel">
            <CardContent className="space-y-4 p-6">
              <div className="space-y-2">
                <h2 className="font-display text-3xl text-ink">
                  {t("export.singlePartyTitle")}
                </h2>
                <p className="text-sm leading-6 text-ink-soft">
                  {t("export.singlePartyBody")}
                </p>
              </div>
              <Button
                className="h-12 px-6 text-base"
                disabled={isPolling}
                size="lg"
                type="button"
                onClick={() => void handleSinglePartyDownload()}
              >
                {isPolling
                  ? t("export.preparingDownload")
                  : t("export.singlePartyCta")}
              </Button>
            </CardContent>
          </Card>
        ) : !hasReadyExport && !exportUnlocked ? null : !hasReadyExport &&
          !canPurchaseExport ? (
          <Card className="app-panel">
            <CardContent className="space-y-3 p-6">
              <h2 className="font-display text-3xl text-ink">
                {t("export.initiatorOnlyTitle")}
              </h2>
              <p className="text-sm leading-6 text-ink-soft">
                {t("export.initiatorOnlyBody")}
              </p>
            </CardContent>
          </Card>
        ) : !hasReadyExport ? (
          <div className="grid gap-4 lg:grid-cols-2">
            <Card className="app-panel">
              <CardContent className="space-y-5 p-6">
                <div className="space-y-2">
                  <h2 className="font-display text-3xl text-ink">
                    {t("export.standardTitle")}
                  </h2>
                  <p className="text-sm leading-6 text-ink-soft">
                    {t("export.standardBody")}
                  </p>
                </div>
                <div className="grid gap-3">
                  {STANDARD_EXPORT_FEATURE_KEYS.map((featureKey) => (
                    <div
                      key={featureKey}
                      className="flex items-center justify-between gap-3 rounded-[1.25rem] bg-surface-soft px-4 py-3"
                    >
                      <span className="text-sm text-ink">{t(featureKey)}</span>
                      <Badge
                        className="border-success/10 bg-success-soft text-success-foreground"
                        variant="secondary"
                      >
                        {t("export.included")}
                      </Badge>
                    </div>
                  ))}
                </div>
                <Button
                  className="h-12 w-full text-base"
                  disabled={isCheckingOut !== null}
                  size="lg"
                  type="button"
                  onClick={() => void handleCheckout("standard")}
                >
                  {isCheckingOut === "standard"
                    ? t("export.redirecting")
                    : t("export.download")}
                </Button>
              </CardContent>
            </Card>

            <Card className="app-panel border-2 border-brand/20">
              <CardContent className="space-y-5 p-6">
                <div className="flex flex-wrap items-center gap-3">
                  <h2 className="font-display text-3xl text-ink">
                    {t("export.resolutionTitle")}
                  </h2>
                  <Badge
                    className="border-brand/15 bg-brand-soft text-brand-strong"
                    variant="secondary"
                  >
                    {t("export.recommended")}
                  </Badge>
                </div>
                <p className="text-sm leading-6 text-ink-soft">
                  {t("export.resolutionBody")}
                </p>
                <div className="grid gap-3">
                  {RESOLUTION_EXPORT_FEATURE_KEYS.map((featureKey) => (
                    <div
                      key={featureKey}
                      className="flex items-center justify-between gap-3 rounded-[1.25rem] bg-surface-soft px-4 py-3"
                    >
                      <span className="text-sm text-ink">{t(featureKey)}</span>
                      <Badge
                        className="border-success/10 bg-success-soft text-success-foreground"
                        variant="secondary"
                      >
                        {t("export.included")}
                      </Badge>
                    </div>
                  ))}
                </div>
                <Button
                  className="h-12 w-full text-base"
                  disabled={isCheckingOut !== null}
                  size="lg"
                  type="button"
                  variant="outline"
                  onClick={() => void handleCheckout("resolution")}
                >
                  {isCheckingOut === "resolution"
                    ? t("export.redirecting")
                    : t("export.upgrade")}
                </Button>
              </CardContent>
            </Card>
          </div>
        ) : null}

        {errorMessage ? (
          <p className="app-alert-danger">{errorMessage}</p>
        ) : null}

        <p className="app-note bg-surface px-5 py-4">
          {t("export.footerNote")}
        </p>
      </div>
    </main>
  );
}
